Aggiunte note Laboratorio 1
Polpetta/MobileProgrammingNotes pull request #11
Opened 2017-06-05 16:03 UTC by GiacomoManzoli

**Reference to the issue (if any)**:  #5 
**Description**
Aggiunti gli appunti relativi al primo laboratorio

2017-06-05 17:37 UTC, Polpetta commented
@mdipirro te ne occupi te? 😊

2017-06-05 17:40 UTC, mdipirro commented
si ma con calma appena riesco

2017-06-05 17:41 UTC, Polpetta commented
Ok nessun problema 👍

2017-06-06 06:19 UTC, mdipirro requested changes
Introduzione ad Android:
Mancano quasi tutti i grafici che sono nelle slides, e i due che ci sono non vengono spiegati abbastanza bene.

Architettura di Android:
Forse il confronto grafico di DVM e ART sarebbe utile.

2017-06-06 08:31 UTC, GiacomoManzoli commented
Ho aggiunto un po' più di spiegazione per i grafici presenti, non ci avevo dato troppo peso perché non mi sembravano molto interessanti.
Eviterei di aggiungerne altri, perché sennò ci sono più immagini che testo. Quelli sulla frammentazione di Android poi non li considererei neanche, tanto alla fine sappiamo tutti benissimo com'è la situazione. 

Ho aggiunto anche l'immagine del confronto Dalvik/ART.

2017-06-07 08:13 UTC, mdipirro approved these changes

2017-06-07 08:13 UTC, merged