Lec2 part1
Polpetta/MobileProgrammingNotes pull request #12
Opened 2017-06-06 06:34 UTC by mzanella

**Reference to the issue (if any)**: #3 

**Description**
Modifica degli appunti riguardati Bluetooth e integrazione appunti wifi direct. Aggiunta appunti riguardanti gli standard 802.11 e 802.15.4, BLE, ZigBee, 6LowPan

2017-06-06 17:09 UTC, Polpetta commented
C'è la parte di @emanueleC?

Il 06 giu 2017 08:34, "mzanella" <notifications@github.com> ha scritto:

> *Reference to the issue (if any)*: #3
> <https://github.com/Polpetta/MobileProgrammingNotes/issues/3>
>
> *Description*
> Modifica degli appunti riguardati Bluetooth e integrazione appunti wifi
> direct. Aggiunta appunti riguardanti gli standard 802.11 e 802.15.4, BLE,
> ZigBee, 6LowPan
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Polpetta/MobileProgrammingNotes/pull/12
> Commit Summary
>
>    - Finita parte wifi direct e bluetooth
>    - riportato documento alle 80 colonne e iniziato 802.15.4
>    - Add missing end itemize
>    - Terminata prima parte lezione 2
>    - Correzione errore ortograafici
>
> File Changes
>
>    - *M* res/sections/12-Cap2.tex
>    <https://github.com/Polpetta/MobileProgrammingNotes/pull/12/files#diff-0>
>    (272)
>
> Patch Links:
>
>    - https://github.com/Polpetta/MobileProgrammingNotes/pull/12.patch
>    - https://github.com/Polpetta/MobileProgrammingNotes/pull/12.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Polpetta/MobileProgrammingNotes/pull/12>, or mute the
> thread
> <https://github.com/notifications/unsubscribe-auth/AFp0903uTQieq0sjiz2is7TNpgoi8jZiks5sBPL4gaJpZM4Nw6ij>
> .
>

2017-06-06 17:50 UTC, EmanueleC commented
@Polpetta no, la mia è in un altro branch. E ho solo aggiunto la parte del web of things, per il momento non ho avuto tempo di inserire altro.

2017-06-06 18:01 UTC, Polpetta commented
Sisi ok, non ci sono problemi!

Il 06 giu 2017 19:50, "Emanuele" <notifications@github.com> ha scritto:

> @Polpetta <https://github.com/polpetta> no, la mia è in un altro branch.
> E ho solo aggiunto la parte del web of things, per il momento non ho avuto
> tempo di inserire altro.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Polpetta/MobileProgrammingNotes/pull/12#issuecomment-306565249>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFp095JqnyLZrYFPdlw3IxrcSROfwThsks5sBZGAgaJpZM4Nw6ij>
> .
>

2017-06-16 16:19 UTC, mdipirro requested changes
-) La figura della divisione dello spettro (pagina 10) è quasi completamente fuori dalla pagina
-) Figura della pila di protocolli 802.11 non centrata
-) BLE quali nuovi profili aggiunge?
-) Ci sono dei conflitti

2017-06-22 11:20 UTC, mdipirro approved these changes

2017-06-22 11:21 UTC, merged