Lab3
Polpetta/MobileProgrammingNotes pull request #14
Opened 2017-06-11 09:28 UTC by Polpetta

**Reference to the issue (if any)**: #6 

**Description**
Scritta questa parte. Ho messo io il codice su github ma e' tutto lavoro di @pasoa94, quindi se ci sono problemi prenditela con lui 😂 
Se non ricordo male e' tutto un set intero, ma ho sbagliato a nominare il branch quando l'ho fatto (pensavo che fosse diviso in piu' parti), quindi ignora il `pt1` alla fine.

2017-06-16 15:45 UTC, mdipirro requested changes
In "Conservare l'oggetto durante il cambiamento" quando dici che "l'uso di una Fragment class è conservata durante il cambiamento" non si capisce bene cosa voglia dire

2017-06-17 08:54 UTC, Polpetta commented
@pasoa94 Tutto per te! 😁

2017-06-23 13:31 UTC, mzanella reviewed
Ho commentato come cambierei io la frase

2017-06-23 13:31 UTC, mzanella commented on res/sections/70-Lab3pt1.tex
> +con lo stato per la nuova istanza. L'uso di una \textit{Fragment} \textit{class}
```
Per mantenere lo stato durante il cambiamento è possibile utilizzare una \textit{Fragment class}.
```

Si può cambiare così?

2017-06-23 13:32 UTC, Polpetta commented on res/sections/70-Lab3pt1.tex
> +con lo stato per la nuova istanza. L'uso di una \textit{Fragment} \textit{class}
:+1: @mdipirro che dici?

2017-06-23 13:34 UTC, mdipirro commented on res/sections/70-Lab3pt1.tex
> +con lo stato per la nuova istanza. L'uso di una \textit{Fragment} \textit{class}
Ok

2017-06-24 07:54 UTC, Polpetta commented on res/sections/70-Lab3pt1.tex
> +con lo stato per la nuova istanza. L'uso di una \textit{Fragment} \textit{class}
@mzanella aggiorna la frase con la tua correzione per favore! Dai che mergiamo anche questa 😏

2017-06-24 08:02 UTC, Polpetta commented
@mdipirro dagli un'occhiata e appena ti va bene approva e mergia

2017-06-24 08:06 UTC, mdipirro approved these changes

2017-06-24 08:06 UTC, merged