Notes integration
Polpetta/MobileProgrammingNotes pull request #15
Opened 2017-06-11 09:44 UTC by Polpetta

**Reference to the issue (if any)**: #2

**Description**
Ho finito di integrare le mie note con quelle di @GiacomoManzoli. Inoltre ho fatto il porting delle note del capitolo 3.

2017-06-16 16:28 UTC, mdipirro requested changes
- C'è ancora da sistemare la questione della sovrapposizione del capitolo 3 con #13 
- Sarebbe meglio se la parte di use cases fosse un po' più approfondita

2017-06-17 10:46 UTC, Polpetta commented
Ci ho dato un'occhiata riguardo a ste _edge network_ perche' sulle slide del prof non si trova nulla a parte una immagine mentre su un paper online ho trovato che significa: `the specifics of what their Internet Service Provider (ISP) gives them in terms of Internet access.`
Il paper in questione lo trovi qui (e' gratis se lo scarichi facendo ponte ssh con i server dell'universita'): http://dl.acm.org/citation.cfm?id=1879173

Penso che sia per quello che Giacomo abbia messo i punti di domanda! La faccenda non e' chiara

2017-06-17 10:49 UTC, mdipirro commented
@Polpetta se hai trovato qualcosa che può togliere i punti di domanda aggiungilo. Sentiamo anche @GiacomoManzoli

2017-06-17 13:01 UTC, Polpetta commented
Si e' che quello che ho trovato non ci sta tantissimo con quello che ha scritto @GiacomoManzoli quindi bisogna capire cosa vogliamo tenere piu' che altro!

2017-06-17 16:03 UTC, GiacomoManzoli commented
Esattamente, i punti di domanda erano presenti perché sulle slide c'è solo una foto e nulla più.
Tra l'altro quella parte se non ricordo male era a fine della prima lezione, ovvero quando l'attenzione era sotto zero.
Siccome non ne ha più parlato, direi che possiamo anche saltarle in pieno (a meno che nel paper di @Polpetta non ci sia qualcosa che in due parole dica cosa sono, ma eviterei tutti i dettagli.

2017-06-17 17:16 UTC, Polpetta commented
L'unica roba che ho trovato nel paper e' la frase che ho scritto sopra! Ovvero:
![image](https://user-images.githubusercontent.com/5928183/27254838-68986684-5391-11e7-9445-f49e48e69c53.png)

2017-06-17 17:23 UTC, GiacomoManzoli commented
E allora direi di lasciare stare

2017-06-17 17:26 UTC, mdipirro commented
Sisi lasciamo stare per carità

2017-06-17 17:44 UTC, Polpetta commented
Ok allora tolgo i punti di domanda e lascio là

Il 17 giu 2017 19:42, "Matteo Di Pirro" <notifications@github.com> ha
scritto:

> Sisi lasciamo stare per carità
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Polpetta/MobileProgrammingNotes/pull/15#issuecomment-309228621>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFp0988UqG4xUFx2eLwF-s-ONBuVuMzWks5sFAw5gaJpZM4N2WFJ>
> .
>

2017-06-20 13:28 UTC, Polpetta commented
Dici che si può mergiare questa pull request?

2017-06-20 13:30 UTC, mdipirro commented
No ci sono ancora da sistemare questi due punti:
- C'è ancora da sistemare la questione della sovrapposizione del capitolo 3 con #13 
- Sarebbe meglio se la parte di use cases fosse un po' più approfondita

2017-06-20 19:39 UTC, Polpetta commented
Okok! 👍 Scusa mi ero dimenticato 😅

2017-06-21 17:33 UTC, Polpetta commented
@mdipirro a sto punto direi che casso via il cap 3 da questa pr, cosi' la possiamo mergiare, e faccio un merge "manuale" del capitolo 3 con le altre due parti che sono in pull requests #18 #13 (ovvero gli do una letta e integro se necessario). Che ne dici?

2017-06-21 17:34 UTC, mdipirro commented
Direi ok. L'importante è che alla fine ci sia tutto e senza duplicati

2017-06-21 22:31 UTC, mdipirro commented
Appena scrivi un pochino di più sugli use cases per me si può fare merge

2017-06-22 08:06 UTC, Polpetta commented
@mdipirro ho aggiunto tutto quello che ho trovato sugli use-case, cercando e aggiungendo anche da fonti esterne. Di più non so che fare! :sweat_smile:

2017-06-22 08:08 UTC, mdipirro commented
Ok dopo pranzo faccio una passata e chiudo il chiudibile

2017-06-22 08:10 UTC, Polpetta commented
Grazie maestro :pray: :1st_place_medal:

2017-06-22 11:00 UTC, mdipirro approved these changes

2017-06-22 11:04 UTC, merged