Lec2 part2
Polpetta/MobileProgrammingNotes pull request #16
Opened 2017-06-20 08:24 UTC by EmanueleC

**Reference to the issue (if any)**: #3 

**Description**  Lezione 2 - Parte 2 : Web of things, Mobile IP, GSM, ...

2017-06-20 08:24 UTC, EmanueleC commented
Maggior parte delle cose aggiunte, apro la PR preventivamente così si può già controllare qualcosa (mi manca pochissimo). Ho scritto tutto in inglese, non credo che tradurrò.

2017-06-20 13:33 UTC, mdipirro commented
Finora direi che ti meriti il titolo di "impiegato del mese"

2017-06-22 09:07 UTC, EmanueleC commented
A meno di correzioni, questo è stato il mio ultimo commit per lec2-part2.
¡hasta luego!

2017-06-22 11:11 UTC, mdipirro requested changes
Forse potresti spiegare un pochino la struttura di una rete GSM. Per il resto ok.

2017-06-23 08:32 UTC, EmanueleC commented
@mdipirro fatto, anche se nelle slides c'erano solo un'immagine e un elenco di caratteristiche/dati buttati lì. Spero basti così.

2017-06-23 08:33 UTC, mdipirro commented
Qualcuno riesce a dare un occhio? Io ora non riesco

2017-06-23 08:34 UTC, EmanueleC commented
@mdipirro posso controllare io se vuoi! :)

2017-06-23 11:59 UTC, mzanella requested changes
rimuovere i `\\` (ma perchè in inglese?)

2017-06-23 12:25 UTC, EmanueleC commented
@mzanella perchè vuoi rimuovere i \\? Non mi piaceva inserire troppe linee bianche, e non mi piaceva avere tutto un blocco di testo così ho dovuto spezzare alcuni punti (e usare \par mi cambiava l'identazione).

2017-06-23 12:32 UTC, EmanueleC commented
Ho messo in inglese perché ero convinto che l'esame fosse in inglese, e perché mi sembra tutto comprensibile (sarebbe stato inutile tradurre). Qualche parola l'ho tradotta, ma solo quelle che ritenevo meno conosciute.

2017-06-23 13:29 UTC, Polpetta approved these changes
Ho letto la parte GSM e a me pare ok! Mi sembra molto più ampliata e spiegata meglio! :+1:

2017-06-23 19:05 UTC, EmanueleC commented
@Polpetta ok! Si può mergiare e chiudere?

2017-06-23 19:34 UTC, Polpetta commented
@EmanueleC io ho detto la mia, senti @mdipirro e @mzanella

2017-06-23 20:01 UTC, GiacomoManzoli commented
Ho dato una letta alla parte del WoT e direi che va bene, mi manca l'altra ma adesso non ho tempo leggerla con la dovuta calma.

Piccola nota, non si può fare niente per migliorare l'impaginazione? Ovvero `\paragraph` al posto dei `\textbf` e meno `\\`? (Siccome sono fisse mie, posso sistemare io domani mattina).

2017-06-23 20:14 UTC, Polpetta commented
@GiacomoManzoli se trovi errori puoi iniziare una review anche se non sei nella lista di quelli richiesti, cosi' indichi esattamente dove sono i problemi in caso.
Io sono arrivato fino al GSM, che pero' devo ancora fare. Il resto mi pareva ok, non ho trovato errori o cose incomprensibili.

2017-06-23 20:15 UTC, EmanueleC commented
@GiacomoManzoli se vuoi sistemare l'impaginazione e rimuovere i \\ (sostituendoli però con qualcosa che mantenga gli spazi attuali) accomodati pure, 👍 io prenderò spunto. Di solito non uso \paragraph perché non mi piace come identa il testo, e uso \\ perché non mi piace inserire troppe linee bianche.

2017-06-23 22:14 UTC, mdipirro approved these changes

2017-06-24 07:55 UTC, Polpetta commented
@mzanella Approva o meno sta pr che la mergiamo!

2017-06-24 08:11 UTC, Polpetta commented
Mergio comunque

2017-06-24 08:11 UTC, merged