Lec3pt2
Polpetta/MobileProgrammingNotes pull request #18
Opened 2017-06-20 18:08 UTC by davideorsini

**Reference to the issue (if any)**: #7 
Aggiunta seconda parte Lec3
**Description**

2017-06-21 22:29 UTC, mdipirro requested changes
Mi sembra ok, ma @Polpetta c'è anche qui la questione che gli argomenti sono duplicati. Quello che hai scritto tu è scritto meglio, ma forse meno approfondito rispetto alle nuove aggiunte.

2017-06-22 07:40 UTC, Polpetta commented
@mdipirro ho rimosso il capitolo tre dal branch `notesIntegration`. Se questo è più approfondito ancora meglio! :blush:

2017-06-22 11:17 UTC, mdipirro commented
@Polpetta bo io vedo ancora la parte vecchia del capitolo 3 sia qui che in #18. Risolvi te sto problema che ho paura di fare casino con i conflitti. Fatto questo si può fare il merge di entrambi, io approvo la revisione intanto.

2017-06-22 11:18 UTC, mdipirro approved these changes

2017-06-23 07:19 UTC, Polpetta commented
@mdipirro anche questa è fatta, non ci sono duplicati con il capitolo 3, mergia appena passa i controlli

2017-06-23 07:23 UTC, merged

2017-06-23 07:23 UTC, Polpetta commented
Stavo per premere io il bottone :disappointed:

2017-06-23 07:24 UTC, mdipirro commented
Ahahaha battuto!! :)